### ISSUE TITLE
Adding 8.1.x-dev to the drupal-core repo

### ISSUE THREAD

**Issue by LennardWesterveld** [drupal-composer/drupal-core#10]
Hi there,

Can 8.1.x-dev be added to this drupal-core repo?
This would be awesome.

Kind regards,
Lennard

**Comment by webflo** [comment]
Enabled 8.1.x and 8.2.x in the build script.

https://github.com/drupal-composer/drupal-core/tree/8.1.x
https://github.com/drupal-composer/drupal-core/tree/8.2.x
