### ISSUE TITLE
Update Drops-8

### ISSUE THREAD

**Issue by RobLoach** [drupal-composer/drupal-core#11]
1. https://github.com/pantheon-systems/drupal-core needs to be updated
2. The issue queue is disable?
3. @greg-1-anderson mind updating it?

**Comment by greg-1-anderson** [comment]
https://github.com/pantheon-systems/drupal-core is not maintained.

Instead of using that project, use https://github.com/drupal-composer/drupal-project, and get your scaffold files from drops-8 rather than Drupal core.

**Comment by derekderaps** [comment]
It seems that the reference to `drupal/core` is baked into scaffolding. I tried ripping it out but no luck so far. See drupal-composer/drupal-scaffold/issues/36

**Comment by RobLoach** [comment]
> https://github.com/pantheon-systems/drupal-core is not maintained.

@greg-1-anderson If you add me as a contributor in there, I'd be more then happy to run an update.

**Comment by greg-1-anderson** [comment]
@derekderaps: You'll still want to pull drupal/core; however, use the `source` option in the `drupal-scaffold` element in your composer.json to point at a drops-8 source, and use `includes` to grab `settings.pantheon.yml` and anything else that you might need.

**Comment by greg-1-anderson** [comment]
@RobLoach: We are not going to maintain the split-core, so I am going to delete this repo from our org. If you'd prefer, I could move it to Kalamuna or somewhere else for you instead.

**Comment by RobLoach** [comment]
@greg-1-anderson Would https://github.com/drupalprojects be a good place for it? /kalamuna would be fine as well.

**Comment by greg-1-anderson** [comment]
The only odd thing about drupalprojects is that the org comment says that the org contains mirrors of drupal.org projects, which this is not. But it does not matter to me; pick a location, and I'll move the project.

**Comment by RobLoach** [comment]
/kalamuna is fine for now, we can move it somewhere else later on if need be. Thanks Greg!

**Comment by greg-1-anderson** [comment]
Interesting problem -- I can only transfer the project to an org where I have admin rights. You can give me temporary admin rights in /kalamuna, or I can make a new temporary org and give us both admin rights there.

**Comment by greg-1-anderson** [comment]
@RobLoach you need to accept my invitation to the transferspiferous org; then, I can make you an admin, and then you can move the project to where you want it.
